### ISSUE TITLE
Hilfe erbeten

### ISSUE THREAD

**Issue by Doedel2000** [AchimKre/venus.dbus-tasmota-smartmeter#10]
Hallo, ich bin kein programmierer und habe respekt vor den ganzen codezeilen.
so sieht meine. lesekopf datenzeile aus:
{"StatusSNS":{"Time":"2024-12-06T11:29:29","MT631":{"Total_in":2295.521,"Total_inT1":0.000,"Total_inT2":0.000,"Power_cur":94,"Power_p1":0,"Power_p2":0,"Power_p3":0,"Total_out":649.380,"Meter_id":""}}
welche daten müssen da wohin eingetragen werden? das ist für mich cryptisch.

Danke
Grüße Martin

**Comment by ZNicoZ** [comment]
hier ein Ausschnitt aus meiner config (funktioniert so einwandfrei).

Ich denke du musst `SML` durch `MT631` ersetzen und bei total_in und total_out auf Groß- Kleinschreibung achten. Außerdem musst du die richtige IP deines Tasmotas angeben.

Mein Tasmota gibt folgende Daten aus, so kannst du es übersetzen..
```
12:37:54.799 MQT: stat/tasmota_65440F/STATUS10 = {"StatusSNS":{"Time":"2024-12-06T12:37:54","SML":{"total_out":1080.626,"total_in":22838.844,"Power_cur":406,"server_id":"0a01484c59020001e73b"}}}
```

Hier meine Config:
```
  def _update(self):   
  
    try:
      meter_url = "http://192.168.1.135/cm?cmnd=status%2010"
      meter_r = requests.get(url=meter_url) # request data from the Tasmota Smartmeter
      meter_data = meter_r.json() # convert JSON data
      #meter_consumption = meter_data['StatusSNS']['MT681']['DJ_TPWRCURR']['DJ_TPWRIN']['DJ_TPWROUT']
      #send data to DBus
      self._dbusservice['/Ac/Power'] = meter_data['StatusSNS']['SML']['Power_cur'] # positive: consumption, negative: feed into grid
      self._dbusservice['/Ac/Current'] = float(meter_data['StatusSNS']['SML']['Power_cur'] / 230 )
      self._dbusservice['/Ac/L1/Voltage'] = 230
       #self._dbusservice['/Ac/L2/Voltage'] = 230
       #self._dbusservice['/Ac/L3/Voltage'] = 230
      self._dbusservice['/Ac/L1/Current'] = float(meter_data['StatusSNS']['SML']['Power_cur'] / 230 )
       #self._dbusservice['/Ac/L2/Current'] = 1
       #self._dbusservice['/Ac/L3/Current'] = 1
      self._dbusservice['/Ac/L1/Power'] = float(meter_data['StatusSNS']['SML']['Power_cur'])
       #self._dbusservice['/Ac/L2/Power'] = 59
       #self._dbusservice['/Ac/L3/Power'] = 59
      self._dbusservice['/Ac/L1/Energy/Forward'] = meter_data['StatusSNS']['SML']['total_in']
       #self._dbusservice['/Ac/L2/Energy/Forward'] = 0.059
       #self._dbusservice['/Ac/L3/Energy/Forward'] = 0.059																  
      self._dbusservice['/Ac/L1/Energy/Reverse'] = meter_data['StatusSNS']['SML']['total_out'] 
      self._dbusservice['/Ac/Energy/Forward'] = self._dbusservice['/Ac/L1/Energy/Forward']
      self._dbusservice['/Ac/Energy/Reverse'] = self._dbusservice['/Ac/L1/Energy/Reverse']
      #logging
      logging.debug("House Consumption (/Ac/Power): %s" % (self._dbusservice['/Ac/Power']))
      logging.debug("House Forward (/Ac/Energy/Forward): %s" % (self._dbusservice['/Ac/Energy/Forward']))
      logging.debug("House Reverse (/Ac/Energy/Revers): %s" % (self._dbusservice['/Ac/Energy/Reverse']))
      logging.debug("---");
       
       # increment UpdateIndex - to show that new data is available
      index = self._dbusservice['/UpdateIndex'] + 1  # increment index
      if index > 255:   # maximum value of the index
       index = 0 # overflow from 255 to 0
      self._dbusservice['/UpdateIndex'] = index

      #update lastupdate vars
      self._lastUpdate = time.time()              
    except Exception as e:
      logging.critical('Error at %s', '_update', exc_info=e)
       
     # return true, otherwise add_timeout will be removed from GObject - see docs http://library.isr.ist.utl.pt/docs/pygtk2reference/gobject-functions.html#function-gobject--timeout-add
    return True
 
  def _handlechangedvalue(self, path, value):
    logging.debug("someone else updated %s to %s" % (path, value))
    return True # accept the change
 


def main():
  #configure logging
  logging.basicConfig(      format='%(asctime)s,%(msecs)d %(name)s %(levelname)s %(message)s',
                            datefmt='%Y-%m-%d %H:%M:%S',
                            level=logging.INFO,
                            handlers=[
                                logging.FileHandler("%s/current.log" % (os.path.dirname(os.path.realpath(__file__)))),
                                logging.StreamHandler()
                            ])
 
  try:
      logging.info("Start");
  
      from dbus.mainloop.glib import DBusGMainLoop
      # Have a mainloop, so we can send/receive asynchronous calls to and from dbus
      DBusGMainLoop(set_as_default=True)
     
      #formatting 
      _kwh = lambda p, v: (str(round(v, 2)) + 'KWh')
      _a = lambda p, v: (str(round(v, 1)) + 'A')
      _w = lambda p, v: (str(round(v, 1)) + 'W')
      _v = lambda p, v: (str(round(v, 1)) + 'V')   
     
      #start our main-service
      pvac_output = DbusSmartmeterService(
        servicename='com.victronenergy.grid',
        deviceinstance=40,
        paths={
          '/Ac/Energy/Forward': {'initial': 0, 'textformat': _kwh}, # energy bought from the grid
          '/Ac/Energy/Reverse': {'initial': 0, 'textformat': _kwh}, # energy sold to the grid
          '/Ac/Power': {'initial': 0, 'textformat': _w},
          
          '/Ac/Current': {'initial': 0, 'textformat': _a},
          '/Ac/Voltage': {'initial': 0, 'textformat': _v},
          
          '/Ac/L1/Voltage': {'initial': 0, 'textformat': _v},
          '/Ac/L2/Voltage': {'initial': 0, 'textformat': _v},
          '/Ac/L3/Voltage': {'initial': 0, 'textformat': _v},
          '/Ac/L1/Current': {'initial': 0, 'textformat': _a},
          '/Ac/L2/Current': {'initial': 0, 'textformat': _a},
          '/Ac/L3/Current': {'initial': 0, 'textformat': _a},
          '/Ac/L1/Power': {'initial': 0, 'textformat': _w},
          '/Ac/L2/Power': {'initial': 0, 'textformat': _w},
          '/Ac/L3/Power': {'initial': 0, 'textformat': _w},
          '/Ac/L1/Energy/Forward': {'initial': 0, 'textformat': _kwh},
          '/Ac/L2/Energy/Forward': {'initial': 0, 'textformat': _kwh},
          '/Ac/L3/Energy/Forward': {'initial': 0, 'textformat': _kwh},
          '/Ac/L1/Energy/Reverse': {'initial': 0, 'textformat': _kwh},
          '/Ac/L2/Energy/Reverse': {'initial': 0, 'textformat': _kwh},
          '/Ac/L3/Energy/Reverse': {'initial': 0, 'textformat': _kwh},
        })
     
      logging.info('Connected to dbus, and switching over to gobject.MainLoop() (= event based)')
      mainloop = gobject.MainLoop()
      mainloop.run()            
  except Exception as e:
    logging.critical('Error at %s', 'main', exc_info=e)
if __name__ == "__main__":
  main()

```

**Comment by Doedel2000** [comment]
schaut eigentlich genau so aus wie bei mir . IP hab ich gleich als erstes eingetragen, SML ersetzt und Total_out ist bei mir groß geschrieben.
def _update(self):

    try:
      meter_url = "http://10.10.10.81/cm?cmnd=status%2010"
      meter_r = requests.get(url=meter_url) # request data from the Tasmota Smartmeter
      meter_data = meter_r.json() # convert JSON data
      #meter_consumption = meter_data['StatusSNS']['MT631']['DJ_TPWRCURR']['DJ_TPWRIN']['DJ_TPWROUT']
      #send data to DBus
      self._dbusservice['/Ac/Power'] = meter_data['StatusSNS']['MT631']['Power_cur'] # positive: consumption, negative: feed into grid
      self._dbusservice['/Ac/Current'] = float(meter_data['StatusSNS']['MT631']['Power_cur'] / 230 )
      self._dbusservice['/Ac/L1/Voltage'] = 230
       #self._dbusservice['/Ac/L2/Voltage'] = 230
       #self._dbusservice['/Ac/L3/Voltage'] = 230
      self._dbusservice['/Ac/L1/Current'] = float(meter_data['StatusSNS']['MT631']['Power_cur'] / 230 )
       #self._dbusservice['/Ac/L2/Current'] = 1
       #self._dbusservice['/Ac/L3/Current'] = 1
      self._dbusservice['/Ac/L1/Power'] = float(meter_data['StatusSNS']['MT631']['Power_cur'])
       #self._dbusservice['/Ac/L2/Power'] = 59
       #self._dbusservice['/Ac/L3/Power'] = 59
      self._dbusservice['/Ac/L1/Energy/Forward'] = meter_data['StatusSNS']['MT631']['Total_in']
       #self._dbusservice['/Ac/L2/Energy/Forward'] = 0.059
       #self._dbusservice['/Ac/L3/Energy/Forward'] = 0.059                                                                                          >
      self._dbusservice['/Ac/L1/Energy/Reverse'] = meter_data['StatusSNS']['MT631']['Total_out']
      self._dbusservice['/Ac/Energy/Forward'] = self._dbusservice['/Ac/L1/Energy/Forward']
      self._dbusservice['/Ac/Energy/Reverse'] = self._dbusservice['/Ac/L1/Energy/Reverse']
      #logging
      logging.debug("House Consumption (/Ac/Power): %s" % (self._dbusservice['/Ac/Power']))
      logging.debug("House Forward (/Ac/Energy/Forward): %s" % (self._dbusservice['/Ac/Energy/Forward']))
      logging.debug("House Reverse (/Ac/Energy/Revers): %s" % (self._dbusservice['/Ac/Energy/Reverse']))
      logging.debug("---");

       # increment UpdateIndex - to show that new data is available
      index = self._dbusservice['/UpdateIndex'] + 1  # increment index
      if index > 255:   # maximum value of the index
       index = 0 # overflow from 255 to 0
      self._dbusservice['/UpdateIndex'] = index

      #update lastupdate vars
      self._lastUpdate = time.time()
    except Exception as e:
      logging.critical('Error at %s', '_update', exc_info=e)

     # return true, otherwise add_timeout will be removed from GObject - see docs http://library.isr.ist.utl.pt/docs/pygtk2reference/gobject-functio>
    return True

  def _handlechangedvalue(self, path, value):
    logging.debug("someone else updated %s to %s" % (path, value))
    return True # accept the change

**Comment by ZNicoZ** [comment]
Gib das mal in einem Browser ein und schau ob du Daten erhältst:
`http://10.10.10.81/cm?cmnd=status%2010`

**Comment by Doedel2000** [comment]
{"StatusSNS":{"Time":"2024-12-06T12:58:33","MT631":{"Total_in":2295.646,"Total_inT1":0.000,"Total_inT2":0.000,"Power_cur":0,"Power_p1":0,"Power_p2":0,"Power_p3":0,"Total_out":649.381,"Meter_id":""}}}

root@nanopi:/data/dbus-tasmota-smartmeter# python /data/dbus-tasmota-smartmeter/dbus-tasmota-smartmeter.py
2024-12-06 11:56:21,143 root INFO Start
2024-12-06 11:56:21,175 root WARNING USING OUTDATED REGISTRATION METHOD!
2024-12-06 11:56:21,186 root WARNING Please set register=False, then call the register method after adding all mandatory paths. See https://github.com/victronenergy/venus/wiki/dbus-api
2024-12-06 11:56:21,192 root CRITICAL Error at main
Traceback (most recent call last):
  File "/data/dbus-tasmota-smartmeter/dbus-tasmota-smartmeter.py", line 144, in main
    pvac_output = DbusSmartmeterService(
  File "/data/dbus-tasmota-smartmeter/dbus-tasmota-smartmeter.py", line 34, in __init__
    self._dbusservice = VeDbusService("{}.http_{:02d}".format(servicename, deviceinstance))
  File "/data/dbus-tasmota-smartmeter/vedbus.py", line 87, in __init__
    self.register()
  File "/data/dbus-tasmota-smartmeter/vedbus.py", line 93, in register
    self._dbusname = dbus.service.BusName(self.name, self._dbusconn, do_not_queue=True)
  File "/usr/lib/python3.8/site-packages/dbus/service.py", line 144, in __new__
    raise NameExistsException(name)
dbus.exceptions.NameExistsException: Bus name already exists: com.victronenergy.grid.http_40
root@nanopi:/data/dbus-tasmota-smartmeter#

**Comment by ZNicoZ** [comment]
hm, bin jetzt ziemlich raus, ich würde aber mal versuchen die device ID zu ändern - die ist ja anscheinend schon vergeben...

`deviceinstance=40,`

**Comment by Doedel2000** [comment]
ich hab einen multiplus gx -- keinen raspberry.

**Comment by Doedel2000** [comment]
Das war die Lösung ...Danke schön ...hab aus 40 41 gemacht ... nun läuft es.

**Comment by Doedel2000** [comment]
jetzt ist mein AKKU weg, wird nicht mehr angezeigt , na super 

geht wieder, schräges victron zeug ;-)
